// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjshFRv7bbFf4lRtnmJBwQos2aOb4S5eg',
    appId: '1:320289664187:android:d8b95f63e97edcb790cd9e',
    messagingSenderId: '320289664187',
    projectId: 'flutter-app-distribution-8dcc9',
    storageBucket: 'flutter-app-distribution-8dcc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0ov4s7yzkktxmWHajK8UxX3yKywDhVo',
    appId: '1:320289664187:ios:f1951a26f5269fb090cd9e',
    messagingSenderId: '320289664187',
    projectId: 'flutter-app-distribution-8dcc9',
    storageBucket: 'flutter-app-distribution-8dcc9.firebasestorage.app',
    iosBundleId: 'com.example.advancedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0ov4s7yzkktxmWHajK8UxX3yKywDhVo',
    appId: '1:320289664187:ios:f1951a26f5269fb090cd9e',
    messagingSenderId: '320289664187',
    projectId: 'flutter-app-distribution-8dcc9',
    storageBucket: 'flutter-app-distribution-8dcc9.firebasestorage.app',
    iosBundleId: 'com.example.advancedApp',
  );
}
